# ---------------------- POKEMON DATA ---------------------- #
"""
This module contains all the static game data including Pokémon stats, 
moves, and type effectiveness.
"""
from typing import List, Dict, Union, Tuple, Optional

# Generation V Pokémon data (simplified for this implementation)
# Format: {id: {"name": str, "types": List[str], "base_stats": Dict, "moves": List[str]}}
POKEMON_DATA = {
    # Unova starters
    1: {"name": "Snivy", "types": ["Grass"], "base_stats": {"hp": 45, "attack": 45, "defense": 55, "sp_attack": 45, "sp_defense": 55, "speed": 63}, 
        "moves": ["Tackle", "Vine Whip", "Leaf Tornado", "Coil"]},
    2: {"name": "Servine", "types": ["Grass"], "base_stats": {"hp": 60, "attack": 60, "defense": 75, "sp_attack": 60, "sp_defense": 75, "speed": 83}, 
        "moves": ["Vine Whip", "Leaf Tornado", "Coil", "Leaf Blade"]},
    3: {"name": "Serperior", "types": ["Grass"], "base_stats": {"hp": 75, "attack": 75, "defense": 95, "sp_attack": 75, "sp_defense": 95, "speed": 113}, 
        "moves": ["Leaf Tornado", "Coil", "Leaf Blade", "Giga Drain"]},
    4: {"name": "Tepig", "types": ["Fire"], "base_stats": {"hp": 65, "attack": 63, "defense": 45, "sp_attack": 45, "sp_defense": 45, "speed": 45}, 
        "moves": ["Tackle", "Ember", "Flame Charge", "Rollout"]},
    5: {"name": "Pignite", "types": ["Fire", "Fighting"], "base_stats": {"hp": 90, "attack": 93, "defense": 55, "sp_attack": 70, "sp_defense": 55, "speed": 55}, 
        "moves": ["Ember", "Flame Charge", "Arm Thrust", "Heat Crash"]},
    6: {"name": "Emboar", "types": ["Fire", "Fighting"], "base_stats": {"hp": 110, "attack": 123, "defense": 65, "sp_attack": 100, "sp_defense": 65, "speed": 65}, 
        "moves": ["Flamethrower", "Hammer Arm", "Heat Crash", "Head Smash"]},
    7: {"name": "Oshawott", "types": ["Water"], "base_stats": {"hp": 55, "attack": 55, "defense": 45, "sp_attack": 63, "sp_defense": 45, "speed": 45}, 
        "moves": ["Tackle", "Water Gun", "Razor Shell", "Aqua Jet"]},
    8: {"name": "Dewott", "types": ["Water"], "base_stats": {"hp": 75, "attack": 75, "defense": 60, "sp_attack": 83, "sp_defense": 60, "speed": 60}, 
        "moves": ["Water Gun", "Razor Shell", "Aqua Jet", "Revenge"]},
    9: {"name": "Samurott", "types": ["Water"], "base_stats": {"hp": 95, "attack": 100, "defense": 85, "sp_attack": 108, "sp_defense": 70, "speed": 70}, 
        "moves": ["Razor Shell", "Aqua Jet", "Megahorn", "Hydro Pump"]},
    
    # Other popular Gen V Pokémon
    10: {"name": "Zoroark", "types": ["Dark"], "base_stats": {"hp": 60, "attack": 105, "defense": 60, "sp_attack": 120, "sp_defense": 60, "speed": 105}, 
         "moves": ["Night Slash", "Foul Play", "Focus Blast", "Flamethrower"]},
    11: {"name": "Volcarona", "types": ["Bug", "Fire"], "base_stats": {"hp": 85, "attack": 60, "defense": 65, "sp_attack": 135, "sp_defense": 105, "speed": 100}, 
         "moves": ["Fiery Dance", "Bug Buzz", "Quiver Dance", "Hurricane"]},
    12: {"name": "Hydreigon", "types": ["Dark", "Dragon"], "base_stats": {"hp": 92, "attack": 105, "defense": 90, "sp_attack": 125, "sp_defense": 90, "speed": 98}, 
         "moves": ["Dragon Pulse", "Dark Pulse", "Flamethrower", "Focus Blast"]},
    13: {"name": "Excadrill", "types": ["Ground", "Steel"], "base_stats": {"hp": 110, "attack": 135, "defense": 60, "sp_attack": 50, "sp_defense": 65, "speed": 88}, 
         "moves": ["Earthquake", "Iron Head", "Rock Slide", "Swords Dance"]},
    14: {"name": "Reshiram", "types": ["Dragon", "Fire"], "base_stats": {"hp": 100, "attack": 120, "defense": 100, "sp_attack": 150, "sp_defense": 120, "speed": 90}, 
         "moves": ["Blue Flare", "Fusion Flare", "Dragon Pulse", "Extrasensory"]},
    15: {"name": "Zekrom", "types": ["Dragon", "Electric"], "base_stats": {"hp": 100, "attack": 150, "defense": 120, "sp_attack": 120, "sp_defense": 100, "speed": 90}, 
         "moves": ["Bolt Strike", "Fusion Bolt", "Dragon Claw", "Zen Headbutt"]},
    16: {"name": "Kyurem", "types": ["Dragon", "Ice"], "base_stats": {"hp": 125, "attack": 130, "defense": 90, "sp_attack": 130, "sp_defense": 90, "speed": 95}, 
         "moves": ["Glaciate", "Dragon Pulse", "Ice Beam", "Earth Power"]},
    17: {"name": "Haxorus", "types": ["Dragon"], "base_stats": {"hp": 76, "attack": 147, "defense": 90, "sp_attack": 60, "sp_defense": 70, "speed": 97}, 
         "moves": ["Dragon Claw", "Dragon Dance", "Earthquake", "Outrage"]},
    18: {"name": "Chandelure", "types": ["Ghost", "Fire"], "base_stats": {"hp": 60, "attack": 55, "defense": 90, "sp_attack": 145, "sp_defense": 90, "speed": 80}, 
         "moves": ["Shadow Ball", "Flamethrower", "Energy Ball", "Psychic"]},
    19: {"name": "Krookodile", "types": ["Ground", "Dark"], "base_stats": {"hp": 95, "attack": 117, "defense": 80, "sp_attack": 65, "sp_defense": 70, "speed": 92}, 
         "moves": ["Earthquake", "Crunch", "Stone Edge", "Dragon Claw"]},
    20: {"name": "Archeops", "types": ["Rock", "Flying"], "base_stats": {"hp": 75, "attack": 140, "defense": 65, "sp_attack": 112, "sp_defense": 65, "speed": 110}, 
         "moves": ["Acrobatics", "Stone Edge", "Dragon Claw", "Earthquake"]},
    21: {"name": "Galvantula", "types": ["Bug", "Electric"], "base_stats": {"hp": 70, "attack": 77, "defense": 60, "sp_attack": 97, "sp_defense": 60, "speed": 108}, 
         "moves": ["Thunder", "Bug Buzz", "Energy Ball", "Sucker Punch"]},
    22: {"name": "Darmanitan", "types": ["Fire"], "base_stats": {"hp": 105, "attack": 140, "defense": 55, "sp_attack": 30, "sp_defense": 55, "speed": 95}, 
         "moves": ["Flare Blitz", "Superpower", "Rock Slide", "Earthquake"]},
    23: {"name": "Scrafty", "types": ["Dark", "Fighting"], "base_stats": {"hp": 65, "attack": 90, "defense": 115, "sp_attack": 45, "sp_defense": 115, "speed": 58}, 
         "moves": ["High Jump Kick", "Crunch", "Dragon Dance", "Ice Punch"]},
    24: {"name": "Jellicent", "types": ["Water", "Ghost"], "base_stats": {"hp": 100, "attack": 60, "defense": 70, "sp_attack": 85, "sp_defense": 105, "speed": 60}, 
         "moves": ["Surf", "Shadow Ball", "Ice Beam", "Recover"]},
    25: {"name": "Ferrothorn", "types": ["Grass", "Steel"], "base_stats": {"hp": 74, "attack": 94, "defense": 131, "sp_attack": 54, "sp_defense": 116, "speed": 20}, 
         "moves": ["Power Whip", "Gyro Ball", "Leech Seed", "Spikes"]},
    26: {"name": "Eelektross", "types": ["Electric"], "base_stats": {"hp": 85, "attack": 115, "defense": 80, "sp_attack": 105, "sp_defense": 80, "speed": 50}, 
         "moves": ["Wild Charge", "Flamethrower", "Crunch", "Giga Drain"]},
    27: {"name": "Braviary", "types": ["Normal", "Flying"], "base_stats": {"hp": 100, "attack": 123, "defense": 75, "sp_attack": 57, "sp_defense": 75, "speed": 80}, 
         "moves": ["Brave Bird", "Superpower", "Rock Slide", "Tailwind"]},
    28: {"name": "Bisharp", "types": ["Dark", "Steel"], "base_stats": {"hp": 65, "attack": 125, "defense": 100, "sp_attack": 60, "sp_defense": 70, "speed": 70}, 
         "moves": ["Iron Head", "Night Slash", "Sucker Punch", "Swords Dance"]},
    29: {"name": "Lilligant", "types": ["Grass"], "base_stats": {"hp": 70, "attack": 60, "defense": 75, "sp_attack": 110, "sp_defense": 75, "speed": 90}, 
         "moves": ["Petal Dance", "Quiver Dance", "Sleep Powder", "Giga Drain"]},
    30: {"name": "Reuniclus", "types": ["Psychic"], "base_stats": {"hp": 110, "attack": 65, "defense": 75, "sp_attack": 125, "sp_defense": 85, "speed": 30}, 
         "moves": ["Psychic", "Focus Blast", "Shadow Ball", "Recover"]}
     
}

# Move data
# Format: {name: {"type": str, "category": str, "power": int, "accuracy": int}}
MOVE_DATA = {
    "Tackle": {"type": "Normal", "category": "Physical", "power": 40, "accuracy": 100},
    "Vine Whip": {"type": "Grass", "category": "Physical", "power": 45, "accuracy": 100},
    "Leaf Tornado": {"type": "Grass", "category": "Special", "power": 65, "accuracy": 90},
    "Coil": {"type": "Poison", "category": "Status", "power": 0, "accuracy": 100, "effect": {"stat_boost": {"attack": 1, "defense": 1, "accuracy": 1}}},
    "Leaf Blade": {"type": "Grass", "category": "Physical", "power": 90, "accuracy": 100},
    "Giga Drain": {"type": "Grass", "category": "Special", "power": 75, "accuracy": 100, "effect": {"drain": 0.5}},
    "Ember": {"type": "Fire", "category": "Special", "power": 40, "accuracy": 100},
    "Flame Charge": {"type": "Fire", "category": "Physical", "power": 50, "accuracy": 100, "effect": {"stat_boost": {"speed": 1}}},
    "Rollout": {"type": "Rock", "category": "Physical", "power": 30, "accuracy": 90},
    "Arm Thrust": {"type": "Fighting", "category": "Physical", "power": 15, "accuracy": 100, "effect": {"multi_hit": [2, 5]}},
    "Heat Crash": {"type": "Fire", "category": "Physical", "power": 80, "accuracy": 100},
    "Flamethrower": {"type": "Fire", "category": "Special", "power": 90, "accuracy": 100},
    "Hammer Arm": {"type": "Fighting", "category": "Physical", "power": 100, "accuracy": 90, "effect": {"stat_boost": {"speed": -1}}},
    "Head Smash": {"type": "Rock", "category": "Physical", "power": 150, "accuracy": 80, "effect": {"recoil": 0.5}},
    "Water Gun": {"type": "Water", "category": "Special", "power": 40, "accuracy": 100},
    "Razor Shell": {"type": "Water", "category": "Physical", "power": 75, "accuracy": 95, "effect": {"stat_drop_chance": {"defense": 1, "chance": 0.5}}},
    "Aqua Jet": {"type": "Water", "category": "Physical", "power": 40, "accuracy": 100, "effect": {"priority": 1}},
    "Revenge": {"type": "Fighting", "category": "Physical", "power": 60, "accuracy": 100},
    "Megahorn": {"type": "Bug", "category": "Physical", "power": 120, "accuracy": 85},
    "Hydro Pump": {"type": "Water", "category": "Special", "power": 110, "accuracy": 80},
     "Night Slash": {"type": "Dark", "category": "Physical", "power": 70, "accuracy": 100},
    "Foul Play": {"type": "Dark", "category": "Physical", "power": 95, "accuracy": 100},
    "Focus Blast": {"type": "Fighting", "category": "Special", "power": 120, "accuracy": 70},
    "Fiery Dance": {"type": "Fire", "category": "Special", "power": 80, "accuracy": 100, "effect": {"stat_boost_chance": {"sp_attack": 1, "chance": 0.5}}},
    "Bug Buzz": {"type": "Bug", "category": "Special", "power": 90, "accuracy": 100, "effect": {"stat_drop_chance": {"sp_defense": 1, "chance": 0.1}}},
    "Quiver Dance": {"type": "Bug", "category": "Status", "power": 0, "accuracy": 100, "effect": {"stat_boost": {"sp_attack": 1, "sp_defense": 1, "speed": 1}}},
    "Hurricane": {"type": "Flying", "category": "Special", "power": 110, "accuracy": 70},
    "Dragon Pulse": {"type": "Dragon", "category": "Special", "power": 85, "accuracy": 100},
    "Dark Pulse": {"type": "Dark", "category": "Special", "power": 80, "accuracy": 100},
    "Earthquake": {"type": "Ground", "category": "Physical", "power": 100, "accuracy": 100},
    "Iron Head": {"type": "Steel", "category": "Physical", "power": 80, "accuracy": 100},
    "Rock Slide": {"type": "Rock", "category": "Physical", "power": 75, "accuracy": 90},
    "Swords Dance": {"type": "Normal", "category": "Status", "power": 0, "accuracy": 100, "effect": {"stat_boost": {"attack": 2}}},
    "Blue Flare": {"type": "Fire", "category": "Special", "power": 130, "accuracy": 85},
    "Fusion Flare": {"type": "Fire", "category": "Special", "power": 100, "accuracy": 100},
    "Extrasensory": {"type": "Psychic", "category": "Special", "power": 80, "accuracy": 100},
    "Bolt Strike": {"type": "Electric", "category": "Physical", "power": 130, "accuracy": 85},
    "Fusion Bolt": {"type": "Electric", "category": "Physical", "power": 100, "accuracy": 100},
    "Dragon Claw": {"type": "Dragon", "category": "Physical", "power": 80, "accuracy": 100},
    "Zen Headbutt": {"type": "Psychic", "category": "Physical", "power": 80, "accuracy": 90},
    "Glaciate": {"type": "Ice", "category": "Special", "power": 65, "accuracy": 95, "effect": {"stat_drop": {"speed": 1}}},
    "Ice Beam": {"type": "Ice", "category": "Special", "power": 90, "accuracy": 100},
    "Earth Power": {"type": "Ground", "category": "Special", "power": 90, "accuracy": 100},
    "Dragon Dance": {"type": "Dragon", "category": "Status", "power": 0, "accuracy": 100, "effect": {"stat_boost": {"attack": 1, "speed": 1}}},
    "Outrage": {"type": "Dragon", "category": "Physical", "power": 120, "accuracy": 100, "effect": {"multi_turn": [2, 3], "confusion": True}},
    "Shadow Ball": {"type": "Ghost", "category": "Special", "power": 80, "accuracy": 100},
    "Energy Ball": {"type": "Grass", "category": "Special", "power": 90, "accuracy": 100},
    "Psychic": {"type": "Psychic", "category": "Special", "power": 90, "accuracy": 100},
    "Crunch": {"type": "Dark", "category": "Physical", "power": 80, "accuracy": 100},
    "Stone Edge": {"type": "Rock", "category": "Physical", "power": 100, "accuracy": 80},
    "Acrobatics": {"type": "Flying", "category": "Physical", "power": 55, "accuracy": 100},
    "Thunder": {"type": "Electric", "category": "Special", "power": 110, "accuracy": 70},
    "Sucker Punch": {"type": "Dark", "category": "Physical", "power": 70, "accuracy": 100, "effect": {"priority": 1}},
    "Flare Blitz": {"type": "Fire", "category": "Physical", "power": 120, "accuracy": 100, "effect": {"recoil": 0.33}},
    "Superpower": {"type": "Fighting", "category": "Physical", "power": 120, "accuracy": 100, "effect": {"stat_drop": {"attack": 1, "defense": 1}}},
    "High Jump Kick": {"type": "Fighting", "category": "Physical", "power": 130, "accuracy": 90},
    "Ice Punch": {"type": "Ice", "category": "Physical", "power": 75, "accuracy": 100},
    "Surf": {"type": "Water", "category": "Special", "power": 90, "accuracy": 100},
    "Recover": {"type": "Normal", "category": "Status", "power": 0, "accuracy": 100, "effect": {"heal": 0.5}},
    "Power Whip": {"type": "Grass", "category": "Physical", "power": 120, "accuracy": 85},
    "Gyro Ball": {"type": "Steel", "category": "Physical", "power": 100, "accuracy": 100},
    "Leech Seed": {"type": "Grass", "category": "Status", "power": 0, "accuracy": 90, "effect": {"leech": True}},
    "Spikes": {"type": "Ground", "category": "Status", "power": 0, "accuracy": 100, "effect": {"entry_hazard": "spikes"}},
    "Wild Charge": {"type": "Electric", "category": "Physical", "power": 90, "accuracy": 100, "effect": {"recoil": 0.25}},
    "Brave Bird": {"type": "Flying", "category": "Physical", "power": 120, "accuracy": 100, "effect": {"recoil": 0.33}},
    "Tailwind": {"type": "Flying", "category": "Status", "power": 0, "accuracy": 100, "effect": {"tailwind": 4}},
    "Petal Dance": {"type": "Grass", "category": "Special", "power": 120, "accuracy": 100, "effect": {"multi_turn": [2, 3], "confusion": True}},
    "Sleep Powder": {"type": "Grass", "category": "Status", "power": 0, "accuracy": 75, "effect": {"status": "sleep"}}
}

    # Type effectiveness chart
TYPE_CHART = {
    "Normal": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Rock": 0.5, "Ghost": 0, "Dragon": 1, "Dark": 1, "Steel": 0.5},
    "Fire": {"Normal": 1, "Fire": 0.5, "Water": 0.5, "Electric": 1, "Grass": 2, "Ice": 2, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 2, "Rock": 0.5, "Ghost": 1, "Dragon": 0.5, "Dark": 1, "Steel": 2},
    "Water": {"Normal": 1, "Fire": 2, "Water": 0.5, "Electric": 1, "Grass": 0.5, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 2, "Flying": 1, "Psychic": 1, "Bug": 1, "Rock": 2, "Ghost": 1, "Dragon": 0.5, "Dark": 1, "Steel": 1},
    "Electric": {"Normal": 1, "Fire": 1, "Water": 2, "Electric": 0.5, "Grass": 0.5, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 0, "Flying": 2, "Psychic": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Dragon": 0.5, "Dark": 1, "Steel": 1},
    "Grass": {"Normal": 1, "Fire": 0.5, "Water": 2, "Electric": 1, "Grass": 0.5, "Ice": 1, "Fighting": 1, "Poison": 0.5, "Ground": 2, "Flying": 0.5, "Psychic": 1, "Bug": 0.5, "Rock": 2, "Ghost": 1, "Dragon": 0.5, "Dark": 1, "Steel": 0.5},
    "Ice": {"Normal": 1, "Fire": 0.5, "Water": 0.5, "Electric": 1, "Grass": 2, "Ice": 0.5, "Fighting": 1, "Poison": 1, "Ground": 2, "Flying": 2, "Psychic": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Dragon": 2, "Dark": 1, "Steel": 0.5},
    "Fighting": {"Normal": 2, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 2, "Fighting": 1, "Poison": 0.5, "Ground": 1, "Flying": 0.5, "Psychic": 0.5, "Bug": 0.5, "Rock": 2, "Ghost": 0, "Dragon": 1, "Dark": 2, "Steel": 2},
    "Poison": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 2, "Ice": 1, "Fighting": 1, "Poison": 0.5, "Ground": 0.5, "Flying": 1, "Psychic": 1, "Bug": 1, "Rock": 0.5, "Ghost": 0.5, "Dragon": 1, "Dark": 1, "Steel": 0},
    "Ground": {"Normal": 1, "Fire": 2, "Water": 1, "Electric": 2, "Grass": 0.5, "Ice": 1, "Fighting": 1, "Poison": 2, "Ground": 1, "Flying": 0, "Psychic": 1, "Bug": 0.5, "Rock": 2, "Ghost": 1, "Dragon": 1, "Dark": 1, "Steel": 2},
    "Flying": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 0.5, "Grass": 2, "Ice": 1, "Fighting": 2, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 2, "Rock": 0.5, "Ghost": 1, "Dragon": 1, "Dark": 1, "Steel": 0.5},
    "Psychic": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 2, "Poison": 2, "Ground": 1, "Flying": 1, "Psychic": 0.5, "Bug": 1, "Rock": 1, "Ghost": 1, "Dragon": 1, "Dark": 0, "Steel": 0.5},
    "Bug": {"Normal": 1, "Fire": 0.5, "Water": 1, "Electric": 1, "Grass": 2, "Ice": 1, "Fighting": 0.5, "Poison": 0.5, "Ground": 1, "Flying": 0.5, "Psychic": 2, "Bug": 1, "Rock": 1, "Ghost": 0.5, "Dragon": 1, "Dark": 2, "Steel": 0.5},
    "Rock": {"Normal": 1, "Fire": 2, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 2, "Fighting": 0.5, "Poison": 1, "Ground": 0.5, "Flying": 2, "Psychic": 1, "Bug": 2, "Rock": 1, "Ghost": 1, "Dragon": 1, "Dark": 1, "Steel": 0.5},
    "Ghost": {"Normal": 0, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 2, "Bug": 1, "Rock": 1, "Ghost": 2, "Dragon": 1, "Dark": 0.5, "Steel": 0.5},
    "Dragon": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Dragon": 2, "Dark": 1, "Steel": 0.5},
    "Dark": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 0.5, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 2, "Bug": 1, "Rock": 1, "Ghost": 2, "Dragon": 1, "Dark": 0.5, "Steel": 0.5},
    "Steel": {"Normal": 1, "Fire": 0.5, "Water": 0.5, "Electric": 0.5, "Grass": 1, "Ice": 2, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Rock": 2, "Ghost": 1, "Dragon": 1, "Dark": 1, "Steel": 0.5}
}

# Additional moves for Gen V Pokémon
   